/**
 * Styled HTML → PDF via Chromium/Edge headless --print-to-pdf.
 */
import { writeFile, mkdir, access } from "node:fs/promises";
import { join } from "node:path";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { platform } from "node:os";
import { pathToFileURL } from "node:url";
import { documentsPath } from "./power.js";
import { ensureDir, getHeyAgentHome } from "@heyagent/shared";

const execFileAsync = promisify(execFile);

export interface ReportSection {
  heading: string;
  body: string;
  source?: string;
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

export function buildReportHtml(
  title: string,
  sections: ReportSection[],
  opts?: { subtitle?: string },
): string {
  const stamp = new Date().toLocaleString("ru-RU");
  const cards = sections
    .map(
      (s, i) => `
    <article class="card">
      <div class="idx">${i + 1}</div>
      <h2>${escapeHtml(s.heading)}</h2>
      <p>${escapeHtml(s.body).replace(/\n/g, "<br/>")}</p>
      ${s.source ? `<a class="src" href="${escapeHtml(s.source)}">${escapeHtml(s.source)}</a>` : ""}
    </article>`,
    )
    .join("\n");

  return `<!DOCTYPE html>
<html lang="ru"><head><meta charset="utf-8"/>
<title>${escapeHtml(title)}</title>
<style>
  @page { margin: 18mm 16mm; }
  :root {
    --ink: #14213d; --muted: #4a5568; --accent: #0d9488; --bg: #f7f5f2; --card: #fff;
  }
  * { box-sizing: border-box; }
  body {
    margin: 0; font-family: "Segoe UI", Georgia, "Times New Roman", serif;
    color: var(--ink); background: var(--bg); line-height: 1.55;
  }
  .hero {
    background: linear-gradient(135deg, #0f766e 0%, #134e4a 55%, #1e293b 100%);
    color: #f8fafc; padding: 2.4rem 2rem 2rem; margin-bottom: 1.5rem;
  }
  .hero h1 { margin: 0 0 .4rem; font-size: 2rem; font-weight: 700; letter-spacing: -0.02em; }
  .hero .sub { opacity: .85; font-size: .95rem; }
  .wrap { max-width: 820px; margin: 0 auto; padding: 0 1.25rem 2rem; }
  .card {
    background: var(--card); border-radius: 14px; padding: 1.1rem 1.25rem 1.1rem 3.2rem;
    margin: 0 0 1rem; position: relative;
    box-shadow: 0 1px 0 rgba(20,33,61,.06), 0 8px 24px rgba(20,33,61,.06);
    border: 1px solid rgba(20,33,61,.06);
    break-inside: avoid;
  }
  .card .idx {
    position: absolute; left: .9rem; top: 1.1rem; width: 1.7rem; height: 1.7rem;
    border-radius: 999px; background: var(--accent); color: #fff;
    font: 700 .85rem/1.7rem "Segoe UI", sans-serif; text-align: center;
  }
  .card h2 { margin: 0 0 .45rem; font-size: 1.15rem; }
  .card p { margin: 0; color: var(--muted); font-size: .98rem; }
  .src { display: inline-block; margin-top: .55rem; font-size: .78rem; color: var(--accent); word-break: break-all; }
  footer { margin-top: 1.5rem; font-size: .75rem; color: #64748b; text-align: center; }
</style></head>
<body>
  <header class="hero"><div class="wrap">
    <h1>${escapeHtml(title)}</h1>
    <div class="sub">${escapeHtml(opts?.subtitle || "HeyAgent research digest")} · ${escapeHtml(stamp)}</div>
  </div></header>
  <main class="wrap">${cards || "<p>Нет секций.</p>"}</main>
  <footer>Generated by HeyAgent</footer>
</body></html>`;
}

async function findChromeLike(): Promise<string | null> {
  const candidates =
    platform() === "win32"
      ? [
          join(process.env["PROGRAMFILES"] || "C:\\Program Files", "Google\\Chrome\\Application\\chrome.exe"),
          join(
            process.env["PROGRAMFILES(X86)"] || "C:\\Program Files (x86)",
            "Google\\Chrome\\Application\\chrome.exe",
          ),
          join(process.env["PROGRAMFILES"] || "C:\\Program Files", "Microsoft\\Edge\\Application\\msedge.exe"),
          join(
            process.env.LOCALAPPDATA || "",
            "Yandex\\YandexBrowser\\Application\\browser.exe",
          ),
        ]
      : platform() === "darwin"
        ? [
            "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
            "/Applications/Microsoft Edge.app/Contents/MacOS/Microsoft Edge",
          ]
        : ["/usr/bin/google-chrome", "/usr/bin/chromium", "/usr/bin/chromium-browser", "/usr/bin/microsoft-edge"];

  for (const c of candidates) {
    if (!c) continue;
    try {
      await access(c);
      return c;
    } catch {
      /* next */
    }
  }
  return null;
}

/** Write styled PDF report; falls back to HTML if no Chromium. */
export async function writeReportPdf(
  title: string,
  sections: ReportSection[],
  destDir?: string,
): Promise<{ path: string; format: "pdf" | "html"; message: string }> {
  const dir = destDir?.trim() || join(documentsPath(), "HeyAgent-Reports");
  await ensureDir(dir, { mkdir } as typeof import("node:fs/promises"));
  const safe = (title || "report").replace(/[^\w\- а-яА-ЯёЁ]+/gi, "_").slice(0, 60).trim() || "report";
  const stamp = new Date().toISOString().slice(0, 19).replace(/[:T]/g, "-");
  const html = buildReportHtml(title, sections);
  const tmpDir = join(getHeyAgentHome(), "tmp");
  await mkdir(tmpDir, { recursive: true });
  const htmlPath = join(tmpDir, `${safe}-${stamp}.html`);
  await writeFile(htmlPath, html, "utf-8");

  const browser = await findChromeLike();
  const pdfPath = join(dir, `${safe}-${stamp}.pdf`);
  if (browser) {
    try {
      await execFileAsync(
        browser,
        [
          "--headless=new",
          "--disable-gpu",
          "--no-pdf-header-footer",
          `--print-to-pdf=${pdfPath}`,
          pathToFileURL(htmlPath).href,
        ],
        { timeout: 60_000 },
      );
      return { path: pdfPath, format: "pdf", message: `Report PDF written: ${pdfPath}` };
    } catch (err) {
      const htmlOut = join(dir, `${safe}-${stamp}.html`);
      await writeFile(htmlOut, html, "utf-8");
      return {
        path: htmlOut,
        format: "html",
        message: `PDF failed (${err instanceof Error ? err.message : String(err)}); HTML written: ${htmlOut}`,
      };
    }
  }

  const htmlOut = join(dir, `${safe}-${stamp}.html`);
  await writeFile(htmlOut, html, "utf-8");
  return {
    path: htmlOut,
    format: "html",
    message: `No Chrome/Edge for PDF; HTML written: ${htmlOut}`,
  };
}

/** Parse markdown-ish content into sections for PDF. */
export function sectionsFromMarkdown(md: string): ReportSection[] {
  const parts = md.split(/\n(?=##\s+)/);
  const sections: ReportSection[] = [];
  for (const p of parts) {
    const m = p.match(/^##\s+(.+)\n([\s\S]*)$/);
    if (m) {
      const body = m[2]!.trim();
      const src = body.match(/https?:\/\/\S+/)?.[0];
      sections.push({ heading: m[1]!.trim(), body: body.replace(src || "", "").trim(), source: src });
    }
  }
  if (!sections.length && md.trim()) {
    sections.push({ heading: "Summary", body: md.trim().slice(0, 4000) });
  }
  return sections;
}
